### ISSUE TITLE
Idea: Easy handling

### ISSUE THREAD

**Issue by Beiri22** [ranweiler/pete#27]
Just an idea.

Right now: tracer.restart(tracee, Restart::Syscall).unwrap();

If the tracee would have a reference to the tracer, you coould allow:
tracee.restart(Restart::Syscall).unwrap();

**Comment by ranweiler** [comment]
This was actually one of the original APIs I considered, and I do like the convenience of having a `self`-receiving `Tracee::restart()` method. We currently wouldn't even need a reference back to the `Ptracer` struct, since the body of `Ptracer::restart()` doesn't actually use the `&mut self`, it just makes a `ptrace()` syscall.

The choice of an `&mut self` receiver encodes the constraint that the `Ptracer` "reserves the right" to read or mutate its internal state on every tracee restart. Also, if you restart a tracee on a thread other than the original tracer's thread, it will result in an OS error (see #3). We use phantom data to make it so `Ptracer` is `!Send`, and thus the current design disallows that error (we could similarly force `Tracee` to be `!Send`, of course).

I settled on the current design as a conservative choice. I wanted to require that a `Ptracer` be a broker between the user and "global resource" of `ptrace()` syscalls, and to have a chance to update metadata about tracees (though we don't currently do that in `restart()`). We could preserve this property via reference back to the `Ptracer`, as you suggested, but we'd probably want that to be a shared `&`, which might then require the introduction of interior mutability in the `Ptracer`.

So, all in all, I'm not sure that the UX benefit is worth the cost. That said, I'll revisit this over the coming weekend, but just wanted to share the original motivation behind the current design.

**Comment by Beiri22** [comment]
I don't want to invalidate all your thoughts, it has just been an idea. It's good to see that you considered this in your original api specifications - and I am looking forward to the weekend :-)

**Comment by ranweiler** [comment]
I did revisit this, and for now, I want to continue requiring the use of the `Ptracer` to restart (for the reasons above). I'm willing to revisit this again in the future, maybe after buttoning down some of the other attach modes. Thanks for prompting me to think about it again, @Beiri22!

**Comment by Beiri22** [comment]
You're welcome!
