### ISSUE TITLE
Add support for reading C strings

### ISSUE THREAD

**Issue by akoptelov** [ranweiler/pete#88]
Some syscalls have `const char *` parameters pointing to a null-terminating string residing in program's memory (in my case, this is [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html)). If the tracing program needs to analyze such parameter's value, it needs somehow to read memory char-by-char, instead of reading a fragment with a specified size.

A workaround would be to manually construct the path to `/proc/[pid]/mem` file, open, seek and read it sequentially.

**Comment by ranweiler** [comment]
Hey @akoptelov, sorry for the huge lag. I'm not getting email notifications for new issues on this repo for some reason.

This is a legit usability pain point. For the intended level of abstraction of this library, I'm wondering if only providing easy `File` access to `/proc/[pid]/mem` might be most appropriate. The rest of the code in your PR could actually work quite generically at that point. Let me mull it over a bit.

**Comment by ranweiler** [comment]
@akoptelov, thank you for your patience. I'm adding a helper in #99 to make this easier, but I don't want to pull the full C string parsing logic into the core tracing library. This isn't because it is particularly complex, but because I want to keep this library as minimal as is reasonable.

Also, thank you for sending a PR! The new `Tracee::memory()` method will be released in 0.11 later today. My thought is that you can use it to easily reimplement your PR's `read_c_string()` method using something like an extension trait on `Tracee`.
