### ISSUE TITLE
Add way to set Ptracer.options

### ISSUE THREAD

**Issue by Timmmm** [ranweiler/pete#96]
First of all can I just say this is an amazing crate, saved me tons of work!

I might be being blind but as far as I can see there's no public way to set `Ptrace.options` to anything other than the default `Options::all()`. Is that intentional?

**Comment by ranweiler** [comment]
@Timmmm, sorry, I never seem to get notifications on this repo!

If there was a reason at some point, I no longer remember it. I probably just thought it would be both misleading (since it only affects newly-spawned tracees) and redundant (because individual tracee options can be set via [`Tracee::set_options()`](https://docs.rs/pete/0.10.0/pete/ptracer/struct.Tracee.html#method.set_options).

That said, I don't see an issue with adding a method like `Ptracer::set_default_options()`. I'll go ahead and add that.

**Comment by ranweiler** [comment]
@Timmmm, thanks for the suggestion, will release this later today in 0.11!

**Comment by Timmmm** [comment]
Thanks!
